services:
  ros2-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2-dev
    tty: true
    stdin_open: true
    runtime: nvidia   # for GPU / RViz / Gazebo
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ./ws:/ws                      # ROS2 workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 GUI
    network_mode: host   # simplifies ROS2 discovery
